import Footer from '@/components/footer/Footer'
import './globals.css'
import styles from "./page.module.css"
import { Inter } from 'next/font/google'
import Header from '@/components/header/Header'
import { Name } from '../../context/MyContext'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Name>
      <div className={styles.mainContainer}>
      
      <Header/>
      {children}
      <Footer />
      </div>
      </Name>

      </body>
    </html>
  )
}
